"""Seed employee achievements (certifications, accomplishments) for demo self-assessment."""

from feedback_cycle import current_review_cycle

SEED_ACHIEVEMENTS = [
    {
        "achievement_id": "ach_seed_001",
        "employee_id": "NX01007",
        "type": "accomplishment",
        "title": "Led pricing experiment for enterprise tier",
        "description": "Ran A/B test across 3 markets; +8% conversion on annual plans.",
        "issuer_or_context": "Core Product · Q1 FY2025",
        "achieved_at": "2025-02-28",
        "review_cycle": "FY2025-H1",
        "visibility": "manager",
        "source": "seed",
    },
    {
        "achievement_id": "ach_seed_002",
        "employee_id": "NX01007",
        "type": "certification",
        "title": "Product Management Certificate (PMI-ACP prep completed)",
        "description": "Completed 24-hour prep programme; exam scheduled Q3.",
        "issuer_or_context": "PMI / internal L&D",
        "achieved_at": "2025-04-10",
        "review_cycle": "FY2025-H1",
        "visibility": "manager",
        "source": "seed",
    },
    {
        "achievement_id": "ach_seed_003",
        "employee_id": "NX01007",
        "type": "project",
        "title": "Customer advisory board — quarterly synthesis",
        "description": "Synthesised feedback from 12 CAB members into roadmap themes for H2.",
        "issuer_or_context": "Product leadership",
        "achieved_at": "2025-05-15",
        "review_cycle": "FY2025-H1",
        "visibility": "manager",
        "source": "seed",
    },
    {
        "achievement_id": "ach_seed_004",
        "employee_id": "NX01007",
        "type": "training",
        "title": "Inclusive feedback for managers (workshop)",
        "description": "",
        "issuer_or_context": "HR · NexaCore L&D",
        "achieved_at": "2025-01-20",
        "review_cycle": "FY2025-H1",
        "visibility": "self",
        "source": "seed",
    },
    {
        "achievement_id": "ach_seed_005",
        "employee_id": "NX01016",
        "type": "certification",
        "title": "Kubernetes Application Developer (CKAD)",
        "description": "",
        "issuer_or_context": "CNCF",
        "achieved_at": "2024-11-05",
        "review_cycle": "FY2025-H1",
        "visibility": "manager",
        "source": "seed",
    },
    {
        "achievement_id": "ach_seed_006",
        "employee_id": "NX01016",
        "type": "accomplishment",
        "title": "Reduced API p95 latency by 35%",
        "description": "Caching layer + query optimisation on orders service.",
        "issuer_or_context": "Platform Engineering",
        "achieved_at": "2025-03-01",
        "review_cycle": "FY2025-H1",
        "visibility": "manager",
        "source": "seed",
    },
    {
        "achievement_id": "ach_seed_007",
        "employee_id": "NX01016",
        "type": "project",
        "title": "On-call runbook automation",
        "description": "Playbooks for top 5 incidents; cut MTTR on P2 incidents.",
        "issuer_or_context": "SRE guild",
        "achieved_at": "2025-04-22",
        "review_cycle": "FY2025-H1",
        "visibility": "manager",
        "source": "seed",
    },
    {
        "achievement_id": "ach_seed_008",
        "employee_id": "NX01016",
        "type": "award",
        "title": "Spot award — incident response",
        "description": "",
        "issuer_or_context": "Engineering leadership",
        "achieved_at": "2025-05-01",
        "review_cycle": "FY2025-H1",
        "visibility": "manager",
        "source": "seed",
    },
    {
        "achievement_id": "ach_seed_009",
        "employee_id": "NX01005",
        "type": "certification",
        "title": "Google Professional Data Engineer",
        "description": "",
        "issuer_or_context": "Google Cloud",
        "achieved_at": "2025-01-15",
        "review_cycle": "FY2025-H1",
        "visibility": "manager",
        "source": "seed",
    },
    {
        "achievement_id": "ach_seed_010",
        "employee_id": "NX01005",
        "type": "accomplishment",
        "title": "Shipped churn prediction model to production",
        "description": "Model v2 in prod; used by CS for renewal prioritisation.",
        "issuer_or_context": "Data Engineering",
        "achieved_at": "2025-02-14",
        "review_cycle": "FY2025-H1",
        "visibility": "manager",
        "source": "seed",
    },
    {
        "achievement_id": "ach_seed_011",
        "employee_id": "NX01005",
        "type": "training",
        "title": "Responsible AI for people managers",
        "description": "",
        "issuer_or_context": "Legal + Data CoP",
        "achieved_at": "2025-03-08",
        "review_cycle": "FY2025-H1",
        "visibility": "manager",
        "source": "seed",
    },
    {
        "achievement_id": "ach_seed_012",
        "employee_id": "NX01005",
        "type": "accomplishment",
        "title": "Mentored 2 analysts on dbt best practices",
        "description": "",
        "issuer_or_context": "Team development",
        "achieved_at": "2025-05-20",
        "review_cycle": "FY2025-H1",
        "visibility": "manager",
        "source": "seed",
    },
    {
        "achievement_id": "ach_seed_013",
        "employee_id": "NX01002",
        "type": "accomplishment",
        "title": "Led pricing experiment for enterprise tier",
        "description": "Ran A/B test across 3 markets; +8% conversion on annual plans.",
        "issuer_or_context": "Core Product · Q1 FY2025",
        "achieved_at": "2025-02-28",
        "review_cycle": "FY2025-H1",
        "visibility": "manager",
        "source": "seed",
    },
    {
        "achievement_id": "ach_seed_014",
        "employee_id": "NX01002",
        "type": "certification",
        "title": "Product Management Certificate (PMI-ACP prep completed)",
        "description": "Completed 24-hour prep programme; exam scheduled Q3.",
        "issuer_or_context": "PMI / internal L&D",
        "achieved_at": "2025-04-10",
        "review_cycle": "FY2025-H1",
        "visibility": "manager",
        "source": "seed",
    },
    {
        "achievement_id": "ach_seed_015",
        "employee_id": "NX01002",
        "type": "project",
        "title": "Customer advisory board — quarterly synthesis",
        "description": "Synthesised feedback from 12 CAB members into roadmap themes for H2.",
        "issuer_or_context": "Product leadership",
        "achieved_at": "2025-05-15",
        "review_cycle": "FY2025-H1",
        "visibility": "manager",
        "source": "seed",
    },
    {
        "achievement_id": "ach_seed_016",
        "employee_id": "NX01002",
        "type": "training",
        "title": "Inclusive feedback for managers (workshop)",
        "description": "",
        "issuer_or_context": "HR · NexaCore L&D",
        "achieved_at": "2025-01-20",
        "review_cycle": "FY2025-H1",
        "visibility": "self",
        "source": "seed",
    },
]


def seed_employee_achievements(repo) -> int:
    cycle = current_review_cycle()
    inserted = 0
    for row in SEED_ACHIEVEMENTS:
        if not repo.get_employee_by_id(row["employee_id"]):
            continue
        aid = row.get("achievement_id")
        if aid and repo.get_achievement(aid):
            continue
        payload = {**row, "review_cycle": cycle}
        repo.insert_achievement(payload)
        inserted += 1
    realigned = repo.realign_seed_achievements_cycle(cycle)
    return inserted + realigned
